name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git remote set-url origin git@hf.co:spaces/microhum/DeepVecFont-TH
      - name: Push to hub
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git push origin --force
